apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      restartPolicy: Always
      containers:
        - name: reverseproxy
          imagePullPolicy: Always
          image: ams2000/reverseproxy:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: 1
          volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true  
      restartPolicy: Always   
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
          optional: false
